In [1]:
import numpy as np
import pandas as pd
from pandas import IndexSlice as idx
import matplotlib.pyplot as plt
from os import listdir

In [2]:
path = "../data/raw/"
years = {}
for year in range(2000, 2020):
    years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")

C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")
C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4145802698.py:4: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  years[year] = pd.read_csv(path+f"{year}/allhlcn{str(year%100).zfill(2)}.csv")

In [3]:
for year in range(2000,2020):
    years[year] = years[year][years[year]["Area Type"] == "County"]

years[2000]

,Area\nCode,St,Cnty,Own,NAICS,Year,Qtr,Area Type,St Name,Area,Ownership,Industry,Annual Average Status Code,Annual Average Establishment Count,Annual Average Employment,Annual Total Wages,Annual Average Weekly Wage,Annual Average Pay,Employment Location Quotient Relative to U.S.,Total Wage Location Quotient Relative to U.S.
34,01001,01,1.0,0,10,2000,A,County,Alabama,"Autauga County, Alabama",Total Covered,"Total, all industries",NaN,818,10770,271408036,485,25200,1.00,1.00
35,01001,01,1.0,1,10,2000,A,County,Alabama,"Autauga County, Alabama",Federal Government,"Total, all industries",NaN,13,98,3182410,625,32501,0.41,0.41
36,01001,01,1.0,2,10,2000,A,County,Alabama,"Autauga County, Alabama",State Government,"Total, all industries",NaN,14,222,6224899,539,28009,0.61,0.66
37,01001,01,1.0,3,10,2000,A,County,Alabama,"Autauga County, Alabama",Local Government,"Total, all industries",NaN,34,1606,42634478,510,26543,1.53,1.76
38,01001,01,1.0,5,10,2000,A,County,Alabama,"Autauga County, Alabama",Private,"Total, all industries",NaN,757,8844,219366249,477,24805,0.97,0.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48268,56045,56.0,45.0,5,1023,2000,A,County,Wyoming,"Weston County, Wyoming",Private,Financial activities,NaN,11,73,1483605,393,20417,0.57,0.31
48269,56045,56.0,45.0,5,1024,2000,A,County,Wyoming,"Weston County, Wyoming",Private,Professional and business services,NaN,13,54,1193045,423,21992,0.19,0.14
48270,56045,56.0,45.0,5,1025,2000,A,County,Wyoming,"Weston County, Wyoming",Private,Education and health services,NaN,13,110,1826126,320,16639,0.45,0.34
48271,56045,56.0,45.0,5,1026,2000,A,County,Wyoming,"Weston County, Wyoming",Private,Leisure and hospitality,NaN,29,242,1746304,139,7216,1.21,0.81
48272,56045,56.0,45.0,5,1027,2000,A,County,Wyoming,"Weston County, Wyoming",Private,Other services,NaN,12,39,584684,287,14928,0.56,0.52

In [4]:
for year in range(2000,2020):
    years[year] = years[year][years[year]["Ownership"] == "Total Covered"]

years[2000]

,Area\nCode,St,Cnty,Own,NAICS,Year,Qtr,Area Type,St Name,Area,Ownership,Industry,Annual Average Status Code,Annual Average Establishment Count,Annual Average Employment,Annual Total Wages,Annual Average Weekly Wage,Annual Average Pay,Employment Location Quotient Relative to U.S.,Total Wage Location Quotient Relative to U.S.
34,01001,01,1.0,0,10,2000,A,County,Alabama,"Autauga County, Alabama",Total Covered,"Total, all industries",NaN,818,10770,271408036,485,25200,1.0,1.0
51,01003,01,3.0,0,10,2000,A,County,Alabama,"Baldwin County, Alabama",Total Covered,"Total, all industries",NaN,4076,48952,1111836793,437,22713,1.0,1.0
68,01005,01,5.0,0,10,2000,A,County,Alabama,"Barbour County, Alabama",Total Covered,"Total, all industries",NaN,683,11909,275633730,445,23146,1.0,1.0
85,01007,01,7.0,0,10,2000,A,County,Alabama,"Bibb County, Alabama",Total Covered,"Total, all industries",NaN,362,3867,83152374,414,21502,1.0,1.0
100,01009,01,9.0,0,10,2000,A,County,Alabama,"Blount County, Alabama",Total Covered,"Total, all industries",NaN,813,9137,206285117,434,22578,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48190,56037,56.0,37.0,0,10,2000,A,County,Wyoming,"Sweetwater County, Wyoming",Total Covered,"Total, all industries",NaN,1258,18710,640570058,658,34237,1.0,1.0
48207,56039,56.0,39.0,0,10,2000,A,County,Wyoming,"Teton County, Wyoming",Total Covered,"Total, all industries",NaN,1801,16438,436479026,511,26553,1.0,1.0
48222,56041,56.0,41.0,0,10,2000,A,County,Wyoming,"Uinta County, Wyoming",Total Covered,"Total, all industries",NaN,671,7961,196570284,475,24693,1.0,1.0
48239,56043,56.0,43.0,0,10,2000,A,County,Wyoming,"Washakie County, Wyoming",Total Covered,"Total, all industries",NaN,425,3559,87712978,474,24645,1.0,1.0
48256,56045,56.0,45.0,0,10,2000,A,County,Wyoming,"Weston County, Wyoming",Total Covered,"Total, all industries",NaN,247,2193,55317171,485,25226,1.0,1.0

In [5]:
for year in range(2000,2020):
    years[year] = years[year][["Area\nCode", "Area", "Annual Average Establishment Count", "Annual Average Employment", "Annual Total Wages",
                                 "Employment Location Quotient Relative to U.S.", "Total Wage Location Quotient Relative to U.S."]]

years[2000]

,Area\nCode,Area,Annual Average Establishment Count,Annual Average Employment,Annual Total Wages,Employment Location Quotient Relative to U.S.,Total Wage Location Quotient Relative to U.S.
34,01001,"Autauga County, Alabama",818,10770,271408036,1.0,1.0
51,01003,"Baldwin County, Alabama",4076,48952,1111836793,1.0,1.0
68,01005,"Barbour County, Alabama",683,11909,275633730,1.0,1.0
85,01007,"Bibb County, Alabama",362,3867,83152374,1.0,1.0
100,01009,"Blount County, Alabama",813,9137,206285117,1.0,1.0
...,...,...,...,...,...,...,...
48190,56037,"Sweetwater County, Wyoming",1258,18710,640570058,1.0,1.0
48207,56039,"Teton County, Wyoming",1801,16438,436479026,1.0,1.0
48222,56041,"Uinta County, Wyoming",671,7961,196570284,1.0,1.0
48239,56043,"Washakie County, Wyoming",425,3559,87712978,1.0,1.0
48256,56045,"Weston County, Wyoming",247,2193,55317171,1.0,1.0

In [6]:
for year in range(2000,2020):
    years[year].dropna(inplace=True)

years[2000]

C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/1982954852.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  years[year].dropna(inplace=True)

,Area\nCode,Area,Annual Average Establishment Count,Annual Average Employment,Annual Total Wages,Employment Location Quotient Relative to U.S.,Total Wage Location Quotient Relative to U.S.
34,01001,"Autauga County, Alabama",818,10770,271408036,1.0,1.0
51,01003,"Baldwin County, Alabama",4076,48952,1111836793,1.0,1.0
68,01005,"Barbour County, Alabama",683,11909,275633730,1.0,1.0
85,01007,"Bibb County, Alabama",362,3867,83152374,1.0,1.0
100,01009,"Blount County, Alabama",813,9137,206285117,1.0,1.0
...,...,...,...,...,...,...,...
48190,56037,"Sweetwater County, Wyoming",1258,18710,640570058,1.0,1.0
48207,56039,"Teton County, Wyoming",1801,16438,436479026,1.0,1.0
48222,56041,"Uinta County, Wyoming",671,7961,196570284,1.0,1.0
48239,56043,"Washakie County, Wyoming",425,3559,87712978,1.0,1.0
48256,56045,"Weston County, Wyoming",247,2193,55317171,1.0,1.0

In [7]:
for year in range(2000,2020):
    years[year].drop(["Employment Location Quotient Relative to U.S.", "Total Wage Location Quotient Relative to U.S."], axis=1, inplace=True)

years[2000]

C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/3565693424.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  years[year].drop(["Employment Location Quotient Relative to U.S.", "Total Wage Location Quotient Relative to U.S."], axis=1, inplace=True)

,Area\nCode,Area,Annual Average Establishment Count,Annual Average Employment,Annual Total Wages
34,01001,"Autauga County, Alabama",818,10770,271408036
51,01003,"Baldwin County, Alabama",4076,48952,1111836793
68,01005,"Barbour County, Alabama",683,11909,275633730
85,01007,"Bibb County, Alabama",362,3867,83152374
100,01009,"Blount County, Alabama",813,9137,206285117
...,...,...,...,...,...
48190,56037,"Sweetwater County, Wyoming",1258,18710,640570058
48207,56039,"Teton County, Wyoming",1801,16438,436479026
48222,56041,"Uinta County, Wyoming",671,7961,196570284
48239,56043,"Washakie County, Wyoming",425,3559,87712978
48256,56045,"Weston County, Wyoming",247,2193,55317171

In [8]:
areas = set.intersection(*[set(years[year]["Area"].values.tolist()) for year in range(2000, 2020)])
len(areas)

3127

In [9]:
for year in range(2000,2020):
	years[year].rename(columns={"Area\nCode":"Area Code"}, inplace=True)

years[2000]

C:\Users\Michael\AppData\Local\Temp/ipykernel_3476/4125864840.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  years[year].rename(columns={"Area\nCode":"Area Code"}, inplace=True)

,Area Code,Area,Annual Average Establishment Count,Annual Average Employment,Annual Total Wages
34,01001,"Autauga County, Alabama",818,10770,271408036
51,01003,"Baldwin County, Alabama",4076,48952,1111836793
68,01005,"Barbour County, Alabama",683,11909,275633730
85,01007,"Bibb County, Alabama",362,3867,83152374
100,01009,"Blount County, Alabama",813,9137,206285117
...,...,...,...,...,...
48190,56037,"Sweetwater County, Wyoming",1258,18710,640570058
48207,56039,"Teton County, Wyoming",1801,16438,436479026
48222,56041,"Uinta County, Wyoming",671,7961,196570284
48239,56043,"Washakie County, Wyoming",425,3559,87712978
48256,56045,"Weston County, Wyoming",247,2193,55317171

In [10]:
for year in range(2000,2020):
    years[year].set_index(["Area Code", "Area"], inplace=True)
    years[year] = years[year].loc[idx[:, list(areas)], :].sort_index()

years[2000]

,,Annual Average Establishment Count,Annual Average Employment,Annual Total Wages
Area Code,Area,,,
01001,"Autauga County, Alabama",818,10770,271408036
01003,"Baldwin County, Alabama",4076,48952,1111836793
01005,"Barbour County, Alabama",683,11909,275633730
01007,"Bibb County, Alabama",362,3867,83152374
01009,"Blount County, Alabama",813,9137,206285117
...,...,...,...,...
56037,"Sweetwater County, Wyoming",1258,18710,640570058
56039,"Teton County, Wyoming",1801,16438,436479026
56041,"Uinta County, Wyoming",671,7961,196570284
56043,"Washakie County, Wyoming",425,3559,87712978
56045,"Weston County, Wyoming",247,2193,55317171

In [11]:
years[2000].index.values

array([('01001', 'Autauga County, Alabama'),
       ('01003', 'Baldwin County, Alabama'),
       ('01005', 'Barbour County, Alabama'), ...,
       ('56041', 'Uinta County, Wyoming'),
       ('56043', 'Washakie County, Wyoming'),
       ('56045', 'Weston County, Wyoming')], dtype=object)

In [12]:
estab = pd.DataFrame(np.nan, index=pd.MultiIndex.from_tuples(years[2000].index.values, names=["Area Code", "Area"]), columns=list(range(2000, 2020)))
for index in years[2000].index.values:
    for year in range(2000,2020):
        estab.loc[index, year] = years[year].loc[index, "Annual Average Establishment Count"]

estab

,,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Area Code,Area,,,,,,,,,,,,,,,,,,,,
01001,"Autauga County, Alabama",818.0,817.0,819.0,802.0,824.0,871.0,863.0,879.0,890.0,877.0,877.0,862.0,842.0,830.0,822.0,845.0,860.0,870.0,871.0,888.0
01003,"Baldwin County, Alabama",4076.0,4121.0,4183.0,4272.0,4536.0,4881.0,5068.0,5337.0,5529.0,5274.0,5171.0,5158.0,5172.0,5247.0,5401.0,5596.0,5822.0,6072.0,6305.0,6471.0
01005,"Barbour County, Alabama",683.0,666.0,636.0,629.0,637.0,633.0,637.0,638.0,639.0,623.0,608.0,598.0,582.0,575.0,568.0,561.0,551.0,555.0,555.0,562.0
01007,"Bibb County, Alabama",362.0,350.0,351.0,341.0,345.0,355.0,357.0,368.0,370.0,348.0,345.0,339.0,349.0,339.0,343.0,338.0,341.0,364.0,374.0,370.0
01009,"Blount County, Alabama",813.0,787.0,755.0,745.0,771.0,810.0,810.0,811.0,811.0,779.0,754.0,740.0,730.0,722.0,715.0,735.0,756.0,772.0,780.0,787.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56037,"Sweetwater County, Wyoming",1258.0,1248.0,1281.0,1321.0,1398.0,1489.0,1628.0,1664.0,1707.0,1723.0,1690.0,1691.0,1703.0,1703.0,1689.0,1685.0,1630.0,1620.0,1616.0,1613.0
56039,"Teton County, Wyoming",1801.0,1864.0,1906.0,1946.0,1992.0,2038.0,2099.0,2141.0,2174.0,2152.0,2134.0,2135.0,2180.0,2194.0,2236.0,2274.0,2304.0,2351.0,2395.0,2457.0
56041,"Uinta County, Wyoming",671.0,691.0,722.0,741.0,773.0,777.0,807.0,810.0,826.0,835.0,815.0,814.0,809.0,791.0,791.0,785.0,764.0,753.0,773.0,768.0
56043,"Washakie County, Wyoming",425.0,425.0,420.0,421.0,418.0,427.0,452.0,459.0,454.0,463.0,467.0,461.0,463.0,460.0,469.0,482.0,478.0,465.0,453.0,442.0
56045,"Weston County, Wyoming",247.0,258.0,257.0,262.0,262.0,266.0,269.0,275.0,280.0,282.0,276.0,272.0,274.0,273.0,274.0,286.0,287.0,278.0,276.0,283.0

In [13]:
estab.isnull().values.any()

False

In [14]:
estab = estab.astype(np.int64)
estab.to_csv("../data/processed/estab.csv")

In [15]:
emp = pd.DataFrame(np.nan, index=pd.MultiIndex.from_tuples(years[2000].index.values, names=["Area Code", "Area"]), columns=list(range(2000, 2020)))
for index in years[2000].index.values:
    for year in range(2000,2020):
        emp.loc[index, year] = years[year].loc[index, "Annual Average Employment"]

emp

,,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Area Code,Area,,,,,,,,,,,,,,,,,,,,
01001,"Autauga County, Alabama",10770.0,11201.0,10838.0,11135.0,11209.0,11452.0,11259.0,11403.0,11273.0,11004.0,10694.0,10627.0,10137.0,10193.0,10458.0,10587.0,10739.0,10823.0,10974.0,11107.0
01003,"Baldwin County, Alabama",48952.0,48971.0,49686.0,51372.0,53451.0,56110.0,59291.0,62600.0,62612.0,58948.0,58140.0,59581.0,60440.0,62719.0,65024.0,67585.0,70107.0,71999.0,74051.0,76419.0
01005,"Barbour County, Alabama",11909.0,11629.0,11145.0,11237.0,10770.0,11132.0,11095.0,10711.0,10321.0,9462.0,9382.0,9044.0,8520.0,8425.0,8166.0,8202.0,7937.0,8012.0,8113.0,8239.0
01007,"Bibb County, Alabama",3867.0,3630.0,3722.0,3831.0,3951.0,4014.0,4092.0,4255.0,4231.0,4037.0,4030.0,4015.0,4130.0,4196.0,4240.0,4075.0,4144.0,4110.0,4215.0,4602.0
01009,"Blount County, Alabama",9137.0,9087.0,8428.0,8232.0,8138.0,8410.0,8572.0,9058.0,9095.0,8603.0,8291.0,8128.0,8203.0,8174.0,7960.0,8066.0,8147.0,8327.0,8535.0,8712.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56037,"Sweetwater County, Wyoming",18710.0,18855.0,18571.0,19453.0,20439.0,21850.0,23889.0,24757.0,25610.0,23920.0,23668.0,24580.0,24877.0,24630.0,24269.0,23590.0,22340.0,22214.0,22275.0,22293.0
56039,"Teton County, Wyoming",16438.0,16736.0,16688.0,16546.0,16730.0,17251.0,17943.0,18445.0,18906.0,17415.0,16938.0,16946.0,17419.0,18107.0,18836.0,19497.0,20232.0,20784.0,20959.0,21429.0
56041,"Uinta County, Wyoming",7961.0,8373.0,8827.0,8695.0,8630.0,8860.0,9386.0,9714.0,10192.0,9576.0,9357.0,8985.0,9127.0,8850.0,8899.0,8720.0,8311.0,8175.0,8219.0,8292.0
56043,"Washakie County, Wyoming",3559.0,3510.0,3524.0,3637.0,3699.0,3827.0,3858.0,3965.0,4076.0,3981.0,3948.0,3957.0,3904.0,3810.0,3782.0,3799.0,3670.0,3630.0,3618.0,3518.0
56045,"Weston County, Wyoming",2193.0,2211.0,2252.0,2151.0,2164.0,2214.0,2165.0,2295.0,2341.0,2269.0,2304.0,2260.0,2293.0,2309.0,2331.0,2345.0,2316.0,2224.0,2269.0,2345.0

In [16]:
emp.isnull().values.any()

False

In [17]:
emp = emp.astype(np.int64)
emp.to_csv("../data/processed/emp.csv")

In [18]:
wage = pd.DataFrame(np.nan, index=pd.MultiIndex.from_tuples(years[2000].index.values, names=["Area Code", "Area"]), columns=list(range(2000, 2020)))
for index in years[2000].index.values:
    for year in range(2000,2020):
        wage.loc[index, year] = years[year].loc[index, "Annual Total Wages"]

wage

,,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Area Code,Area,,,,,,,,,,,,,,,,,,,,
01001,"Autauga County, Alabama",2.714080e+08,2.864787e+08,2.853804e+08,2.945100e+08,3.088284e+08,3.159159e+08,3.274017e+08,3.443618e+08,3.480483e+08,3.436715e+08,3.395072e+08,3.443560e+08,3.415135e+08,3.463020e+08,3.579964e+08,3.721219e+08,3.905431e+08,4.039734e+08,4.214710e+08,4.480782e+08
01003,"Baldwin County, Alabama",1.111837e+09,1.148224e+09,1.209948e+09,1.285592e+09,1.400816e+09,1.556506e+09,1.748925e+09,1.884880e+09,1.927159e+09,1.812254e+09,1.813333e+09,1.867343e+09,1.926968e+09,2.039249e+09,2.153975e+09,2.289993e+09,2.406000e+09,2.542348e+09,2.724885e+09,2.926329e+09
01005,"Barbour County, Alabama",2.756337e+08,2.675653e+08,2.579447e+08,2.714248e+08,2.758309e+08,2.897230e+08,3.015286e+08,3.069493e+08,3.036864e+08,2.810492e+08,2.840201e+08,2.836429e+08,2.741414e+08,2.770346e+08,2.776860e+08,2.874882e+08,2.805687e+08,2.864298e+08,3.099956e+08,3.079464e+08
01007,"Bibb County, Alabama",8.315237e+07,8.388880e+07,9.146683e+07,9.664842e+07,1.059043e+08,1.105254e+08,1.172358e+08,1.287477e+08,1.313597e+08,1.261509e+08,1.334843e+08,1.352947e+08,1.433587e+08,1.509955e+08,1.581926e+08,1.536725e+08,1.627596e+08,1.637432e+08,1.689918e+08,1.978229e+08
01009,"Blount County, Alabama",2.062851e+08,2.100331e+08,2.036282e+08,2.022116e+08,2.088680e+08,2.221403e+08,2.395944e+08,2.551284e+08,2.649246e+08,2.514206e+08,2.418144e+08,2.415930e+08,2.490826e+08,2.530300e+08,2.611831e+08,2.681071e+08,2.751013e+08,2.882213e+08,3.039430e+08,3.123669e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56037,"Sweetwater County, Wyoming",6.405701e+08,6.733217e+08,6.751980e+08,7.309942e+08,7.955457e+08,9.196223e+08,1.099886e+09,1.200298e+09,1.319501e+09,1.178987e+09,1.214886e+09,1.332108e+09,1.388779e+09,1.385053e+09,1.420422e+09,1.375045e+09,1.257096e+09,1.288821e+09,1.310772e+09,1.343821e+09
56039,"Teton County, Wyoming",4.364790e+08,4.733274e+08,4.823821e+08,5.055410e+08,5.258395e+08,5.691707e+08,6.361462e+08,6.843289e+08,7.338955e+08,6.615964e+08,6.442745e+08,6.609992e+08,6.979313e+08,7.330300e+08,8.001027e+08,8.292140e+08,8.910643e+08,9.486097e+08,1.009490e+09,1.105112e+09
56041,"Uinta County, Wyoming",1.965703e+08,2.203407e+08,2.463575e+08,2.489240e+08,2.517624e+08,2.751440e+08,3.164625e+08,3.639256e+08,4.035225e+08,3.806023e+08,3.993130e+08,3.620490e+08,3.745708e+08,3.925311e+08,3.737875e+08,3.592044e+08,3.280886e+08,3.258169e+08,3.343123e+08,3.484748e+08
56043,"Washakie County, Wyoming",8.771298e+07,8.926476e+07,9.089003e+07,9.455379e+07,1.046719e+08,1.115493e+08,1.195533e+08,1.317262e+08,1.389523e+08,1.372108e+08,1.396591e+08,1.458424e+08,1.495564e+08,1.473479e+08,1.517783e+08,1.528806e+08,1.474982e+08,1.478015e+08,1.477388e+08,1.497843e+08
56045,"Weston County, Wyoming",5.531717e+07,5.700938e+07,5.961558e+07,5.375481e+07,5.507371e+07,5.755859e+07,6.260771e+07,7.533173e+07,8.147800e+07,7.330326e+07,7.890950e+07,7.986839e+07,8.192941e+07,8.368364e+07,8.720734e+07,9.041758e+07,8.575228e+07,8.547185e+07,9.290597e+07,9.985924e+07

In [19]:
wage.isnull().values.any()

False

In [20]:
wage = wage.astype(np.int64)
wage.to_csv("../data/processed/wage.csv")